pipeline {
    agent none

    stages {
        stage('Build') {
            steps {
                echo 'Building the project...'
                
                sh 'echo "Build process complete"'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
               
                sh 'echo "Tests are successful"'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
                // Insert your deployment commands here
                sh 'echo "Deployment complete"'
            }
        }
    }

    post {
        always {
            echo 'This will always run after the stages, for cleanup or notifications.'
        }
        success {
            echo 'Pipeline succeeded!'
        }  
    }
}
