pipeline {
    agent any
     tools{
     gradle 'Gradle-6.2'
     }
    stages {
        stage('checkout'){
            steps{
                echo 'Checkout From the Jenkins-Repo '
            }
        }
        stage('Build-FrontEnd') {
            steps {
                
                echo 'Building the project...'
                
                bat 'echo "Build process complete"'
                node('NodeJS-22.9'){
                    bat 'yarn install'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
               
                bat 'echo "Tests are successful"'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
                // Insert your deployment commands here
                bat'echo "Deployment complete"'
                bat 'gradle -v'
            }
        }
    }

    post {
        always {
            echo 'This will always run after the stages, for cleanup or notifications.'
        }
        success {
            echo 'Pipeline succeeded!'
        }  
    }
}
