pipeline{
    agent any
    environment{
         env.NEW_VARIBLE="GOWSHIK"
         env.BRANCH_NAME='main'
    }

    stages{
        stage("Deployment"){
            steps{
                echo "Hello World"
            }
        }
        stage("Built"){
            when{
                expression{
                    env.BRANCH_NAME == 'main'
                }
            }
            steps{
                echo "${env.NEW_VARIBLE}"
            }

        }
    }
    post{
        always{
            echo "Completed"
        }
       
    }
}
